joint_limits:
  fr3_joint1:
    has_position_limits: true
    min_position: -2.7437
    max_position:  2.7437
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: true
    max_acceleration: 10.0
  fr3_joint2:
    has_position_limits: true
    min_position: -1.7837
    max_position:  1.7837
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: true
    max_acceleration: 10.0
  fr3_joint3:
    has_position_limits: true
    min_position: -2.9007
    max_position:  2.9007
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: true
    max_acceleration: 10.0
  fr3_joint4:
    has_position_limits: true
    min_position: -3.0421
    max_position: -0.1518
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: true
    max_acceleration: 10.0
  fr3_joint5:
    has_position_limits: true
    min_position: -2.8065
    max_position:  2.8065
    has_velocity_limits: true
    max_velocity: 5.26
    has_acceleration_limits: true
    max_acceleration: 10.0
  fr3_joint6:
    has_position_limits: true
    min_position:  0.5445
    max_position:  4.5169
    has_velocity_limits: true
    max_velocity: 4.18
    has_acceleration_limits: true
    max_acceleration: 10.0
  fr3_joint7:
    has_position_limits: true
    min_position: -3.0159
    max_position:  3.0159
    has_velocity_limits: true
    max_velocity: 5.26
    has_acceleration_limits: true
    max_acceleration: 10.0
